# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - ademkesmez

on:
  push:
    branches:
      - ademkesmez
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_f4880352c0fd430a933f18b37cf97641 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_757c29d01ee5415f978409628f89044a }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_f4880352c0fd430a933f18b37cf97641 }}/azure-app-service/windows/parkingpage:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'ademkesmez'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_082a10b3859f482da7ec13d4bbe5a91d }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_f4880352c0fd430a933f18b37cf97641 }}/azure-app-service/windows/parkingpage:${{ github.sha }}'